// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbkprtfdoeoazfgmsecm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZia3BydGZkb2VvYXpmZ21zZWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjkzOTgsImV4cCI6MjA3MjI0NTM5OH0.cKfliAwLAH8eId-7mM9y3J6yi3ACmFPa9U4SQA87AHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});